version: '3'
services:
  redis:
    image: redis
  web:
    # COMPLETE HERE
    image: v4resk/project_devops
    ports:
      - "5000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
