---
- hosts: all
  # Run commands as root
  become: yes


  tasks:
  # Tasks to be executed on these hosts
  - name: Install Node.js and npm.
    yum:
      name: npm
      state: present

  - name: Install Forever (to run our Node.js app).
    npm:
      name: forever
      global: yes
      state: present
  
  - name: Install redis
    yum:
      name: redis
      state: present
  
  
  - name: Install app dependencies
    npm:
      path: "/userapi"

  
  - name: Start the app
    command: "forever start /home/vagrant/userapi/index.js"
  
  #Roles to be executed
  roles: 
  - role: healthchecks
    tags: checks


  
