apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    application: noderedis
    component: redis-server
    type: single
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    application: noderedis
    component: redis-server
    type: single
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    application: noderedis
    component: webservice
spec:
  type: NodePort
  selector:
    application: noderedis
    component: webservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 30000
    
