---
- hosts: all
  # Run commands as root
  become: yes


  tasks:
  # Tasks to be executed on these hosts
  - name: Install Node.js and npm.
    yum:
      name: npm
      state: present
  
  - name: Install redis
    yum:
      name: redis
      state: present
  
  # Roles to be executed
  roles: 
  - role: healthchecks
    tags: checks


  
